
with  DOCUMENT_ID_TEMP as(
    select *,
    ROW_NUMBER() OVER (PARTITION BY _id ORDER BY UPDATEDATETIME DESC) AS rn
    from 
    REECO.MONGO.DOCUMENTSERVICE_DOCUMENTS

)
    
select 
_ID DOCUMENT_ID,
JSON_EXTRACT_PATH_TEXT(INVOICENUMBER, 'Value') AS INVOICENUMBER,
ORDERID,
CASE 
    WHEN REGEXP_LIKE(JSON_EXTRACT_PATH_TEXT(INVOICEDATE, 'Value')::STRING, '^[0-9]+$')
    THEN TO_TIMESTAMP_NTZ(CAST(JSON_EXTRACT_PATH_TEXT(INVOICEDATE, 'Value')::STRING AS NUMBER) / 1000)
    ELSE NULL 
END AS INVOICEDATE,
UPDATEDATETIME,
JSON_EXTRACT_PATH_TEXT(SUPPLIERNAME, 'Value') AS SUPPLIER_NAME,
JSON_EXTRACT_PATH_TEXT(REECOSUPPLIER, 'SupplierId') AS SUPPLIER_id,
BUYERNAME,
JSON_EXTRACT_PATH_TEXT(TOTALPRODUCTSPRICE, 'Value') AS TOTALPRODUCTSPRICE,
ISDELETED AS ISDELETED,
ISDEMO,
STATUS,
BUYERID as BUYER_ID,
flattened_items.VALUE:CatalogItemId::STRING AS CatalogItemId,
flattened_items.VALUE:Name:Value::STRING AS document_item_name,
flattened_items.VALUE:Sku:Value::STRING AS document_Sku,
flattened_items.VALUE:OrderQuantity:Value::STRING document_Item_Quantity,
flattened_items.VALUE:TotalPrice:Value::STRING document_Item_Price

from DOCUMENT_ID_TEMP,

LATERAL FLATTEN(INPUT => LINEITEMS) AS flattened_items

where  rn = 1
  