with  DOCUMENT_ID_TEMP as(
    select *,
    ROW_NUMBER() OVER (PARTITION BY _id ORDER BY UPDATEDATETIME DESC) AS rn
    from 
    REECO.MONGO.DOCUMENTSERVICE_DOCUMENTS

    )
    
select 
_ID DOCUMENT_ID,
JSON_EXTRACT_PATH_TEXT(INVOICENUMBER, 'Value') AS INVOICENUMBER,
ORDERID,
CASE 
    WHEN REGEXP_LIKE(JSON_EXTRACT_PATH_TEXT(INVOICEDATE, 'Value')::STRING, '^[0-9]+$')
    THEN TO_TIMESTAMP_NTZ(CAST(JSON_EXTRACT_PATH_TEXT(INVOICEDATE, 'Value')::STRING AS NUMBER) / 1000)
    ELSE NULL 
END AS INVOICEDATE,
UPDATEDATETIME,
JSON_EXTRACT_PATH_TEXT(SUPPLIERNAME, 'Value') AS SUPPLIERNAME,
BUYERNAME,
JSON_EXTRACT_PATH_TEXT(TOTALPRODUCTSPRICE, 'Value') AS TOTALPRODUCTSPRICE,
ISDELETED AS ISDELETED,
ISDEMO,
STATUS,
BUYERID

from DOCUMENT_ID_TEMP
where  rn = 1
