name: "reeco_analytics"
version: "1.0.0"
config-version: 2

profile: "reeco"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"

models:
  reeco_analytics:        
    base:
      +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table
