select
    ORDER_ID,
    CATALOG_ITEM_ID,
    ITEM_NAME,
    ORDER_CREATED_DATE,
    CREATED_DATE_ITEM,
    RECIEVED_DATE_ITEM,
    GLCODE_ITEM,
    EXPENSE_NAME_ITEM,
    QUANTITY_PACKING_ORDERED_ITEM,
    QUANTITY_PACKING_RECIEVED_ITEM,
    PRICE_PER_PACKING_ORDERED_ITEM,
    PRICE_PER_PACKING_RECIEVED_ITEM,
    TOTAL_PRICE_ORDERED_ITEM,
    TOTAL_PRICE_RECIEVED_ITEM


from
    {{ref("base_order_unified")}}
